//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TameMyCerts.WSTEP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TameMyCerts.WSTEP.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one {0} account with {1} of {2} was found in the directory..
        /// </summary>
        internal static string DirVal_Invalid_Result_Count {
            get {
                return ResourceManager.GetString("DirVal_Invalid_Result_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} account with {1} of {2} was found in the directory. Search root is {3}..
        /// </summary>
        internal static string DirVal_Nothing_Found {
            get {
                return ResourceManager.GetString("DirVal_Nothing_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory query {0} in {1} failed because {2}.
        /// </summary>
        internal static string DirVal_Query_Failed {
            get {
                return ResourceManager.GetString("DirVal_Query_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A certificate request was denied because {0}
        ///
        ///Client User Name: {1}
        ///Client IP Address: {2}
        ///Client User Agent: {3}
        ///Request URI: {4}
        ///Request HTTP Method: {5}.
        /// </summary>
        internal static string ERR_REQUEST_DENIED {
            get {
                return ResourceManager.GetString("ERR_REQUEST_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception has occurred. The exception message is: {0}
        ///
        ///Client User Name: {1}
        ///Client IP Address: {2}
        ///Client User Agent: {3}
        ///Request URI: {4}
        ///Request HTTP Method: {5}
        ///
        ///The full stack trace is as follows:
        ///
        ///{6}.
        /// </summary>
        internal static string ERR_UNHANDLED_EXCEPTION {
            get {
                return ResourceManager.GetString("ERR_UNHANDLED_EXCEPTION", resourceCulture);
            }
        }
    }
}
